services:
  - type: web
    name: newsletter-builder
    runtime: python
    rootDir: newsletter-builder
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
